url: "https://jeanyijinwang.github.io"
baseurl: "/"
# Site settings
title: Jean's Portfolio
email: yijinwang1992@gmail.com
description: "Yijin Wang's Portfoliio"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/jeanyijinwang/
  - title: github
    url: https://github.com/jeanyijinwang
  - title: envelope
    url: mailto:jean.yijinwang@gmail.com

# Postal address (add as many lines as necessary)

# Build settings
markdown: kramdown
permalink: pretty
